apiVersion: v1
kind: Service
metadata:
  name: fastapi-weather  # Match your app name here
spec:
  selector:
    app: fastapi-weather  # Must match metadata.labels.app in Deployment
  ports:
    - protocol: TCP
      port: 80            
      targetPort: 8000    
  type: LoadBalancer       
  # LoadBalancer is suitable for cloud environments to expose the service externally