name: CI - Terraform & Kubernetes Code Validation

on:
  push:
    paths:
      - 'terraform/**'
      - 'k8s/**'
  pull_request:
    paths:
      - 'terraform/**'
      - 'k8s/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init (no backend)
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan (no refresh)
        run: terraform plan -refresh=false

      - name: Install kubeval
        run: |
          curl -sLO https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
          tar -xzf kubeval-linux-amd64.tar.gz
          chmod +x kubeval
          sudo mv kubeval /usr/local/bin/

      - name: Validate Kubernetes manifests with kubeval
        run: kubeval k8s/**/*.yaml
