name: Release → build, verify, deploy

on:
  release:
    types: [published]  # Trigger only when you publish a release

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-weather
  RELEASE_TAG: ${{ github.event.release.tag_name }}

jobs:
  build-push:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.RELEASE_TAG }}
            ${{ env.IMAGE_NAME }}:latest
          build-args: |
            APP_VERSION=${{ env.RELEASE_TAG }}

  verify-version:
    needs: build-push
    runs-on: self-hosted
    steps:
      - name: Pull & run container locally
        run: |
          docker run -d --name test -e APP_VERSION=${{ env.RELEASE_TAG }} -p 18000:8000 ${{ env.IMAGE_NAME }}:${{ env.RELEASE_TAG }}
          sleep 10

      - name: Check /api/hello version matches tag
        run: |
          ver=$(curl -s http://localhost:18000/api/hello | jq -r '.version')
          if [ "$ver" != "${{ env.RELEASE_TAG }}" ]; then
            echo "Version mismatch: $ver vs ${{ env.RELEASE_TAG }}"
            exit 1
          fi

      - name: Cleanup test container
        run: docker rm -f test

  deploy-compose:
    needs: verify-version
    runs-on: self-hosted
    steps:
      - name: Show repo files
        run: ls -al
      - name: Copy docker-compose.yaml to VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: docker-compose.yaml
          target: /home/${{ secrets.DEPLOY_USER }}/fastapi-weather/
          port: 22
          debug: true
